# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_al9FV6w1urRqpmT4W9nV7KdH95FwMNW
"""



# ==========================================================
# 🚀 N-HiTS (v2) - Yüksek MAPE ve Negatif Tahmin Çözümü
#
# Değişiklikler:
# 1. Hedef değişkene log(1+x) dönüşümü uygulandı (Daha stabil veri dağılımı).
# 2. Modelin çıktı katmanına ReLU aktivasyonu eklendi (Negatif tahminleri önleme).
# 3. Model 50 yerine 100 epok eğrilecek (Yeni dağılıma alışması için).
# ==========================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import RobustScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

# ---- Reprodüksiyon ----
SEED = 42
tf.keras.utils.set_random_seed(SEED)

# ---- Kritik Değişkenler ----
LOG_TRANSFORM_TARGET = True # Log dönüşümünü etkinleştir

# ==========================================================
# 1) N-HiTS Blok (Düzenli)
# ==========================================================
L2 = keras.regularizers.l2(1e-4)

class NHiTSBlock(layers.Layer):
    """N-HiTS Temel Bloğu: Pooling + Regülarize MLP + LayerNorm + Backcast/Forecast"""
    def __init__(self, units, num_layers, pool_size, backcast_length, forecast_length, drop=0.2, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.num_layers = num_layers
        self.pool_size = pool_size
        self.backcast_length = backcast_length
        self.forecast_length = forecast_length
        self.drop = drop

        # N-HiTS: Multi-Rate Pooling
        self.pooling = layers.MaxPooling1D(pool_size=self.pool_size, padding='same') if self.pool_size and self.pool_size > 1 else None
        self.flatten = layers.Flatten()

        # MLP: Dense + LayerNorm + Dropout (L2 ile)
        self.mlp_layers = []
        for i in range(self.num_layers):
            self.mlp_layers += [
                layers.Dense(self.units, activation='relu', kernel_regularizer=L2, name=f'mlp_dense_{i}'),
                layers.LayerNormalization(name=f'ln_{i}'),
                layers.Dropout(self.drop, name=f'drop_{i}')
            ]

        # Basis Fonksiyonları (Regülarize edilmiş)
        self.theta_b = layers.Dense(self.backcast_length, kernel_regularizer=L2, name='theta_backcast')
        self.theta_f = layers.Dense(self.forecast_length, kernel_regularizer=L2, name='theta_forecast')

    def call(self, x, training=False):
        h = self.pooling(x) if self.pooling is not None else x
        h = self.flatten(h)
        for layer in self.mlp_layers:
            # Dropout sadece training modunda aktif olmalı
            h = layer(h, training=training) if isinstance(layer, layers.Dropout) else layer(h)

        # Backcast çıktısı (B, backcast_len, 1) şekline getirilir
        backcast = tf.expand_dims(self.theta_b(h), axis=-1)
        forecast = self.theta_f(h)
        return backcast, forecast

def build_nhits(backcast_len, forecast_len, n_feats,
                num_stacks=3, blocks_per_stack=2, num_layers=2, layer_size=128,
                pooling_sizes=(8,4,1), drop=0.2):
    """N-HiTS Çoklu Yığın Mimarisi"""
    inp = layers.Input(shape=(backcast_len, n_feats), name='input')
    residuals = inp
    forecasts = []

    # Hedef (ilk sütun) ve Dışsal (kalan) sütunları ayırma
    get_first = layers.Lambda(lambda t: t[:, :, 0:1])
    get_rest  = layers.Lambda(lambda t: t[:, :, 1:])

    for s in range(num_stacks):
        ps = pooling_sizes[s] if s < len(pooling_sizes) else 1
        for b in range(blocks_per_stack):
            blk = NHiTSBlock(layer_size, num_layers, ps, backcast_len, forecast_len, drop=drop, name=f'stack{s}_block{b}')
            backcast, forecast = blk(residuals)

            # Residual Connection: Backcast sadece hedef sütundan çıkarılır (Appliances)
            res_first = get_first(residuals)
            res_first = layers.Subtract()([res_first, backcast])

            # Diğer 14 özellik residual'a olduğu gibi eklenir (bağlamsal bilgi)
            if n_feats > 1:
                res_rest = get_rest(residuals)
                residuals = layers.Concatenate(axis=-1)([res_first, res_rest])
            else:
                residuals = res_first

            forecasts.append(forecast)

    out = layers.Add(name='ensemble')(forecasts) if len(forecasts) > 1 else forecasts[0]

    # 🌟 YENİLİK: Negatif Tahminleri Önlemek İçin ReLU Aktivasyonu
    out = layers.Activation('relu', name='relu_output')(out)

    return keras.Model(inp, out, name='NHiTS_V2')

# ==========================================================
# 2) Veri Hazırlama (15 Özellikli Set)
# ==========================================================
df = pd.read_csv('/content/drive/MyDrive/energydata_complete.csv')

# Tarih işleme ve Cyclical Encoding
df['date'] = pd.to_datetime(df['date'], dayfirst=True, errors='coerce')
df["hour"] = df["date"].dt.hour
df["day_of_week"] = df["date"].dt.dayofweek
df["hour_sin"] = np.sin(2*np.pi*df["hour"]/24)
df["hour_cos"] = np.cos(2*np.pi*df["hour"]/24)
df["day_sin"]  = np.sin(2*np.pi*df["day_of_week"]/7)
df["day_cos"]  = np.cos(2*np.pi*df["day_of_week"]/7)

# Rolling / Lag (Hedef: Appliances)
if "Appliances" not in df.columns:
    raise ValueError("Veride 'Appliances' kolonu yok.")

# 🌟 YENİLİK: Log Dönüşümü Uygulanıyor
if LOG_TRANSFORM_TARGET:
    df["Appliances"] = np.log1p(df["Appliances"])
    print("✅ Hedef Değişken: log(1+Appliances) dönüşümü uygulandı.")

# Rolling/Lag Feature Engineering (Artık log dönüşümlü veriden hesaplanacak)
for w in [6, 12, 24]:
    df[f"roll_mean_{w}"] = df["Appliances"].rolling(w, min_periods=1).mean()
    df[f"roll_std_{w}"]  = df["Appliances"].rolling(w, min_periods=1).std().fillna(0)
for lag in [1, 6, 12]:
    df[f"lag_{lag}"] = df["Appliances"].shift(lag)

df = df.dropna().reset_index(drop=True)

# Özellik seti (15 özellik, hedef ilk sütun olmalı)
feats = [
    "Appliances",
    "hour_sin","hour_cos","day_sin","day_cos",
    "T_out","RH_out","Windspeed",
    "roll_mean_6","roll_std_6",
    "roll_mean_12","roll_std_12",
    "lag_1","lag_6","lag_12"
]
feats = [c for c in feats if c in df.columns]
print(f"✅ Kullanılan özellik sayısı: {len(feats)}")

data = df[feats].values

# RobustScaler (sadece train'e fit)
scaler = RobustScaler()

LOOKBACK = 96
HORIZON  = 12

def make_seq(arr, lb, hz):
    X, y = [], []
    for i in range(len(arr) - lb - hz + 1):
        X.append(arr[i:i+lb])
        y.append(arr[i+lb:i+lb+hz, 0])  # hedef: ilk sütun (Appliances)
    return np.asarray(X, np.float32), np.asarray(y, np.float32)

# Zaman sıralı böl
N = len(data)
train_end = int(N*0.70)
val_end   = int(N*0.85)

train_raw = data[:train_end]
val_raw   = data[train_end:val_end]
test_raw  = data[val_end:]

train_scaled = scaler.fit_transform(train_raw)
val_scaled   = scaler.transform(val_raw)
test_scaled  = scaler.transform(test_raw)

X_train, y_train = make_seq(train_scaled, LOOKBACK, HORIZON)
X_val,   y_val   = make_seq(val_scaled,   LOOKBACK, HORIZON)
X_test,  y_test  = make_seq(test_scaled,  LOOKBACK, HORIZON)

print("\n📊 Dataset:")
print("   Train:", X_train.shape)
print("   Val:  ", X_val.shape)
print("   Test: ", X_test.shape)

# ==========================================================
# 3) Model + Eğitim (anti-overfit)
# ==========================================================
# 🌟 YENİLİK: V2 Modelini Oluştur
model = build_nhits(
    backcast_len=LOOKBACK,
    forecast_len=HORIZON,
    n_feats=X_train.shape[-1],
    num_stacks=3, blocks_per_stack=2,
    num_layers=2, layer_size=128,
    pooling_sizes=(8,4,1), drop=0.2
)

optimizer = keras.optimizers.Adam(learning_rate=1e-3, clipnorm=1.0)
model.compile(optimizer=optimizer, loss='huber', metrics=['mae'])

# Callbacks:
os.makedirs("/content/nhits_ckpt_v2", exist_ok=True)
ckpt_path = "/content/drive/MyDrive/THEBESTMODEL.h5"
callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True), # Sabrı 3'ten 5'e çıkardık
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=1, min_lr=1e-6),
    ModelCheckpoint(filepath=ckpt_path, monitor='val_loss', save_best_only=True, verbose=0),
]

print("\n🚀 N-HiTS V2 Eğitimi Başlıyor (Log Transform + ReLU Çıkış)...")
history = model.fit(
    X_train, y_train,
    epochs=100, # Epok sayısını artırdık
    batch_size=256,
    validation_data=(X_val, y_val),
    callbacks=callbacks,
    verbose=2
)

# ==========================================================
# 4) Değerlendirme + Görselleştirme (Tüm Ufuk Dahil)
# ==========================================================
# En iyi ağırlıklar otomatik olarak yüklendi
y_pred = model.predict(X_test, batch_size=256, verbose=0)

def inverse_first(values):
    """RobustScaler ters dönüşümü ve Log ters dönüşümü (exp(x)-1)"""
    # values shape: (N, H) -> (N*H, 1) -> (N*H, 15)

    N_samples = values.shape[0]
    H = values.shape[1] if values.ndim > 1 else 1
    dummy = np.zeros((N_samples * H, len(feats)), dtype=np.float32)

    if values.ndim > 1:
        dummy[:, 0] = values.flatten()
    else:
        dummy[:, 0] = values

    # 1. Ters Ölçekleme (RobustScaler)
    scaled_inv = scaler.inverse_transform(dummy)[:, 0].reshape(N_samples, H)

    # 2. 🌟 YENİLİK: Log ters dönüşümü (exp(x) - 1)
    if LOG_TRANSFORM_TARGET:
        result_inv = np.expm1(scaled_inv)
    else:
        result_inv = scaled_inv

    # Negatif değerleri 0'a kısıtla (zaten ReLU ile kısıtlandı ama bu ekstra güvenlik)
    result_inv[result_inv < 0] = 0
    return result_inv

# Gerçek değerleri ve tahminleri ters ölçekle
y_true_inv_all = inverse_first(y_test)
y_pred_inv_all = inverse_first(y_pred)

# Residual (Hata)
residual_all = y_true_inv_all - y_pred_inv_all

# Metrikler
# 1) Sadece İlk Adım (t+1)
mae_1 = np.mean(np.abs(residual_all[:, 0]))
rmse_1 = np.sqrt(np.mean(residual_all[:, 0]**2))
# MAPE hesaplarken 0'a bölme hatasını önlemek için küçük bir epsilon eklenir
mape_1 = np.mean(np.abs(residual_all[:, 0] / (np.abs(y_true_inv_all[:, 0]) + 1e-8))) * 100

# 2) Tüm Ufuk (t+1'den t+12'ye)
mae_all = np.mean(np.abs(residual_all))
rmse_all = np.sqrt(np.mean(residual_all**2))
mape_all = np.mean(np.abs(residual_all / (np.abs(y_true_inv_all) + 1e-8))) * 100

print(f"\n==================================================================")
print(f"✅ N-HiTS Test Performansı (Horizon={HORIZON} Adım) - V2 (Log+ReLU)")
print(f"==================================================================")
print(f"🎯 1. Adım (t+1) Metrikleri:")
print(f"   MAE:  {mae_1:.3f} Wh")
print(f"   RMSE: {rmse_1:.3f} Wh (RMSE/MAE oranı: {rmse_1/mae_1:.2f})")
print(f"   MAPE: {mape_1:.2f}%")
print(f"------------------------------------------------------------------")
print(f"🎯 Tüm Ufuk (t+1 - t+{HORIZON}) ORTALAMA Metrikleri:")
print(f"   Ort. MAE:  {mae_all:.3f} Wh")
print(f"   Ort. RMSE: {rmse_all:.3f} Wh (RMSE/MAE oranı: {rmse_all/mae_all:.2f})")
print(f"   Ort. MAPE: {mape_all:.2f}%")
print(f"==================================================================")

# Görselleştirme
fig, axes = plt.subplots(2, 1, figsize=(16, 12))

# 1. Ana tahmin grafiği (Sadece İlk Adım)
time_steps = range(len(y_true_inv_all))
axes[0].plot(time_steps, y_true_inv_all[:, 0], label="Gerçek Değer ($t+1$)", linewidth=1.5, alpha=0.8, color='#0077B6')
axes[0].plot(time_steps, y_pred_inv_all[:, 0], label="N-HiTS Tahmini ($t+1$)", linewidth=1.5, alpha=0.8, color='#FF9F1C')
axes[0].set_title("N-HiTS V2: Enerji Tüketimi Tahmini (Sadece İlk Adım $t+1$ Karşılaştırması)", fontsize=14, fontweight='bold')
axes[0].set_ylabel("Enerji Tüketimi (Wh)")
axes[0].set_xlabel("Test Seti Örnekleri (96 Adım Penceresi)")
axes[0].legend(loc='upper right'); axes[0].grid(True, alpha=0.3)

# 2. Hata (RMSE) Ufuk Boyunca Dağılımı
horizon_rmse = [np.sqrt(np.mean(residual_all[:, i]**2)) for i in range(HORIZON)]
horizon_steps = [f"t+{i+1}" for i in range(HORIZON)]

axes[1].bar(horizon_steps, horizon_rmse, color='#4CAF50', alpha=0.8)
axes[1].bar(horizon_steps[0], horizon_rmse[0], color='#D81B60', label=f't+1 RMSE ({rmse_1:.3f})')
axes[1].set_title(f"RMSE'nin Tahmin Ufku Boyunca Değişimi (Horizon: {HORIZON} Adım)", fontsize=14, fontweight='bold')
axes[1].set_xlabel("Tahmin Adımı")
axes[1].set_ylabel("RMSE (Wh)")
axes[1].grid(axis='y', alpha=0.5)
axes[1].legend()

plt.tight_layout()
plt.show()

def _generate_plot_image():
    import io
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    return buf.read()



# ==========================================================
# 🔍 Modelin Öğrenme ve Genelleme Analizi + Bölgesel Metrikler
# ==========================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import RobustScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# ==========================================================
# 1️⃣ Modelin özel katmanı (birebir seninkiyle aynı)
# ==========================================================
L2 = keras.regularizers.l2(1e-4)
class NHiTSBlock(layers.Layer):
    def __init__(self, units, num_layers, pool_size, backcast_length, forecast_length, drop=0.2, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.num_layers = num_layers
        self.pool_size = pool_size
        self.backcast_length = backcast_length
        self.forecast_length = forecast_length
        self.drop = drop
        self.pooling = layers.MaxPooling1D(pool_size=self.pool_size, padding='same') if self.pool_size and self.pool_size > 1 else None
        self.flatten = layers.Flatten()
        self.mlp_layers = []
        for i in range(self.num_layers):
            self.mlp_layers += [
                layers.Dense(self.units, activation='relu', kernel_regularizer=L2, name=f'mlp_dense_{i}'),
                layers.LayerNormalization(name=f'ln_{i}'),
                layers.Dropout(self.drop, name=f'drop_{i}')
            ]
        self.theta_b = layers.Dense(self.backcast_length, kernel_regularizer=L2, name='theta_backcast')
        self.theta_f = layers.Dense(self.forecast_length, kernel_regularizer=L2, name='theta_forecast')

    def call(self, x, training=False):
        h = self.pooling(x) if self.pooling is not None else x
        h = self.flatten(h)
        for layer in self.mlp_layers:
            h = layer(h, training=training) if isinstance(layer, layers.Dropout) else layer(h)
        backcast = tf.expand_dims(self.theta_b(h), axis=-1)
        forecast = self.theta_f(h)
        return backcast, forecast

# ==========================================================
# 2️⃣ Model ve test verisini yükle
# ==========================================================
MODEL_PATH = "/content/drive/MyDrive/THEBESTMODEL.h5"
DATA_PATH = "/content/drive/MyDrive/energy_test_challenging.csv"

print("✅ Veriler yükleniyor...")
df = pd.read_csv(DATA_PATH)
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["hour"] = df["date"].dt.hour
df["day_of_week"] = df["date"].dt.dayofweek
df["hour_sin"] = np.sin(2*np.pi*df["hour"]/24)
df["hour_cos"] = np.cos(2*np.pi*df["hour"]/24)
df["day_sin"]  = np.sin(2*np.pi*df["day_of_week"]/7)
df["day_cos"]  = np.cos(2*np.pi*df["day_of_week"]/7)

# Feature engineering
df["Appliances"] = np.log1p(df["Appliances"])
for w in [6, 12, 24]:
    df[f"roll_mean_{w}"] = df["Appliances"].rolling(w, min_periods=1).mean()
    df[f"roll_std_{w}"]  = df["Appliances"].rolling(w, min_periods=1).std().fillna(0)
for lag in [1, 6, 12]:
    df[f"lag_{lag}"] = df["Appliances"].shift(lag)
df = df.dropna().reset_index(drop=True)

feats = [
    "Appliances",
    "hour_sin","hour_cos","day_sin","day_cos",
    "T_out","RH_out","Windspeed",
    "roll_mean_6","roll_std_6",
    "roll_mean_12","roll_std_12",
    "lag_1","lag_6","lag_12"
]
data = df[feats].values

LOOKBACK, HORIZON = 96, 12
scaler = RobustScaler()
scaled = scaler.fit_transform(data)

# Dizi oluştur
def make_seq(arr, lb, hz):
    X, y = [], []
    for i in range(len(arr) - lb - hz + 1):
        X.append(arr[i:i+lb])
        y.append(arr[i+lb:i+lb+hz, 0])
    return np.asarray(X, np.float32), np.asarray(y, np.float32)

X, y = make_seq(scaled, LOOKBACK, HORIZON)

# Veri böl
N = len(X)
train_end = int(N * 0.7)
val_end = int(N * 0.85)

X_train, y_train = X[:train_end], y[:train_end]
X_val, y_val     = X[train_end:val_end], y[train_end:val_end]
X_test, y_test   = X[val_end:], y[val_end:]

# Modeli yükle
model = keras.models.load_model(MODEL_PATH, compile=False, custom_objects={'NHiTSBlock': NHiTSBlock})
print("✅ Model yüklendi:", MODEL_PATH)

# ==========================================================
# 3️⃣ Tahmin yap ve ters dönüşüm
# ==========================================================
def inverse_first(values):
    N_samples, H = values.shape
    dummy = np.zeros((N_samples * H, len(feats)))
    dummy[:, 0] = values.flatten()
    scaled_inv = scaler.inverse_transform(dummy)[:, 0].reshape(N_samples, H)
    result_inv = np.expm1(scaled_inv)
    result_inv[result_inv < 0] = 0
    return result_inv

y_pred_train = model.predict(X_train, batch_size=256, verbose=0)
y_pred_val   = model.predict(X_val, batch_size=256, verbose=0)
y_pred_test  = model.predict(X_test, batch_size=256, verbose=0)

y_train_inv = inverse_first(y_train)
y_val_inv   = inverse_first(y_val)
y_test_inv  = inverse_first(y_test)

y_pred_train_inv = inverse_first(y_pred_train)
y_pred_val_inv   = inverse_first(y_pred_val)
y_pred_test_inv  = inverse_first(y_pred_test)

# ==========================================================
# 4️⃣ Görselleştir + Metrik Tablosu
# ==========================================================
fig, ax = plt.subplots(figsize=(16,6))

ax.plot(np.arange(len(y_train_inv)), y_train_inv[:,0], color='#0077B6', label='Train Gerçek')
ax.plot(np.arange(len(y_train_inv)), y_pred_train_inv[:,0], '--', color='#0096C7', label='Train Tahmin')

ax.plot(np.arange(len(y_train_inv), len(y_train_inv)+len(y_val_inv)), y_val_inv[:,0], color='#F9C74F', label='Val Gerçek')
ax.plot(np.arange(len(y_train_inv), len(y_train_inv)+len(y_val_inv)), y_pred_val_inv[:,0], '--', color='#F9844A', label='Val Tahmin')

ax.plot(np.arange(len(y_train_inv)+len(y_val_inv), len(y_train_inv)+len(y_val_inv)+len(y_test_inv)), y_test_inv[:,0], color='#D00000', label='Test Gerçek')
ax.plot(np.arange(len(y_train_inv)+len(y_val_inv), len(y_train_inv)+len(y_val_inv)+len(y_test_inv)), y_pred_test_inv[:,0], '--', color='#9D0208', label='Test Tahmin')

ax.set_title("📊 Modelin Öğrenme ve Genelleme Davranışı (Train/Val/Test)")
ax.set_xlabel("Zaman Adımı")
ax.set_ylabel("Enerji Tüketimi (Wh)")
ax.legend()
ax.grid(alpha=0.3)

# ==========================================================
# 5️⃣ Bölgesel Metrik Analizi (Train / Val / Test)
# ==========================================================
def metrics(y_true, y_pred):
    residual = y_true - y_pred
    mae = np.mean(np.abs(residual))
    rmse = np.sqrt(np.mean(residual ** 2))
    mape = np.mean(np.abs(residual / (np.abs(y_true) + 1e-8))) * 100
    return mae, rmse, mape

results = []
for name, yt, yp in [
    ("Train", y_train_inv[:,0], y_pred_train_inv[:,0]),
    ("Val",   y_val_inv[:,0],   y_pred_val_inv[:,0]),
    ("Test",  y_test_inv[:,0],  y_pred_test_inv[:,0])
]:
    mae, rmse, mape = metrics(yt, yp)
    results.append([name, mae, rmse, mape, rmse/mae])

# Terminal çıktısı
print("\n================= 📊 Bölgesel Performans =================")
print(" Bölge    |    MAE    |   RMSE   |   MAPE   | RMSE/MAE ")
print("----------------------------------------------------------")
for r in results:
    print(f"{r[0]:<8} | {r[1]:7.3f} | {r[2]:7.3f} | {r[3]:7.2f}% | {r[4]:4.2f}")
print("==========================================================")

# ==========================================================
# 6️⃣ Tabloyu grafiğin altına çiz
# ==========================================================
table_data = [[r[0], f"{r[1]:.3f}", f"{r[2]:.3f}", f"{r[3]:.2f}%", f"{r[4]:.2f}"] for r in results]
columns = ["Bölge", "MAE", "RMSE", "MAPE", "RMSE/MAE"]
table = plt.table(cellText=table_data, colLabels=columns, cellLoc='center', loc='bottom', bbox=[0.0, -0.45, 1, 0.25])
table.auto_set_font_size(False)
table.set_fontsize(10)
plt.subplots_adjust(left=0.1, bottom=0.3)
plt.show()